{% set version = "1.9.9" %}

package:
  name: django-autoslug
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-autoslug/django-autoslug-{{ version }}.tar.gz
  sha256: 79f88e9433c1c88d8d3f2bec60d65ca98bffaff6c072b78aa5fd99d0e84a13dd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - django >=1.11

test:
  commands:
    - pip check
    - python -c "import django; from django.conf import settings; settings.configure(); django.setup(); import autoslug"
  requires:
    - pip

about:
  home: http://bitbucket.org/neithere/django-autoslug/
  license: LGPL-3.0-or-later
  license_file: COPYING.LESSER
  summary: An automated slug field for Django

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
    - kcemenike
