{% set name = "django-autoslug" %}
{% set version = "1.9.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-autoslug-{{ version }}.tar.gz
  sha256: 79f88e9433c1c88d8d3f2bec60d65ca98bffaff6c072b78aa5fd99d0e84a13dd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=40.6.0
    - poetry-core
    - pip
  run:
    - python >=3.6

test:
  commands:
    - pip check
    - python -c "import django; from django.conf import settings; settings.configure(); django.setup(); import autoslug"
  requires:
    - pip

about:
  home: http://bitbucket.org/neithere/django-autoslug/
  license: LGPL-3.0-or-later
  license_file: COPYING.LESSER
  summary: An automated slug field for Django

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
    - kcemenike
